#ifndef BOARD_FAMILY_H
#define BOARD_FAMILY_H

#define SPLC_DEVICE_CLASS_UNKNOWN       0
#define SPLC_DEVICE_CLASS_REMOTE_IO     0
#define SPLC_DEVICE_CLASS_DATALOGGER    0
#define SPLC_DEVICE_CLASS_GATEWAY       0
#define SPLC_DEVICE_CLASS_CONTROLLER    0

#ifdef SPLC_DEVICE_CLASS_REMOTE_IO
typedef enum {
    SPLC_REMOTE_IO_VARIANT_UNKNOWN     = 0,
    SPLC_REMOTE_IO_VARIANT_8DI_8DO_4AI = 1,
    SPLC_REMOTE_IO_VARIANT_16DI_16DO   = 2
} SPLC_RemoteIoVariant;
#endif

#ifdef SPLC_DEVICE_CLASS_DATALOGGER
typedef enum {
    SPLC_DATALOGGER_VARIANT_UNKNOWN = 0,
    SPLC_DATALOGGER_VARIANT_8AI     = 1
} SPLC_DataloggerVariant;
#endif

#ifdef SPLC_DEVICE_CLASS_GATEWAY
typedef enum {
    SPLC_GATEWAY_VARIANT_UNKNOWN   = 0,
    SPLC_GATEWAY_VARIANT_RS485_ETH = 1
} SPLC_GatewayVariant;
#endif

#endif